### PR TITLE
Position and floating Element Project

### PR DESCRIPTION
**Pull request by DanSam5K**
- Set up the repository and tools
- Prepare the assets for your website
>Content: text, images, icons, links
Fonts and colors
- Took to come up with website skeleton
- Complete markup & simple styling 
-Then  Use flexbox to position elements on the screen.
-Then completed final touches before deployment and submission for PR
-Added a Read me file to understand what the project

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

Hi @DanSam5K :wave: 

It's impressive to see how well you've done considering it's your first project at Microverse 👍 👏
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED ♻️ 

##### Navigation Bar

* [x] The New York Times logo in the navbar should be a link (have `a` tag)

##### Bottom part (right above the footer)

* [x] Articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) should have an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute, 
* [x] The `Most Popular` articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) should have an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute.
* [x] Elements should be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)). You only made use of flex. 

## OPTIONAL
* [x] Add some margin to the left and right side of the footer



> ### "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by DanSam5K** [comment]
Thank you at Lei

> # Status: Changes Required ♻️
> Hi @DanSam5K 👋
> 
> It's impressive to see how well you've done considering it's your first project at Microverse 👍 👏
> However, there are still some changes to be made before this milestone can be approved.
> 
> ## REQUIRED ♻️
> ##### Navigation Bar
> * [x]  The New York Times logo in the navbar should be a link (have `a` tag)
> 
> ##### Bottom part (right above the footer)
> * [x]  Articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) should have an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute,
> * [x]  The `Most Popular` articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) should have an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute.
> * [x]  Elements should be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)). You only made use of flex.
> 
> ## OPTIONAL
> * [x]  Add some margin to the left and right side of the footer
> 
> > ### "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."
> 
> ## Happy Coding 💻
> _Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
> **Elijah O. Ayandokun**
> [Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

Thank you for the feed back will will Effect the changes right away Sir!

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @DanSam5K :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by DanSam5K** [comment]
### Thank you for the feedback it means alot! my first approval :clap: :clap: :clap:

**Pull request merged**
